### ISSUE TITLE
Support typed array geometries

### ISSUE THREAD

**Issue by dmnsgn** [vorg/geom-triangulate#1]
You have support for triangulating polygons but that won't fly with typed arrays so we can either:
- pass a stride argument and assume faces are all the same sizes
- pass an array of offsets for each polygons
- drop polygon support and assume quads

**Comment by vorg** [comment]
I would say if cells is typed array we assume it's triangles. 

I can imagine a scenario where positions/normals are flat typed arrays but cells is array of polygons (Array of Arrays/UInt32Arrays) but as of today we don't have code producing such meshes.
